# Exercícios Numpy

## Problema 1. 
Crie um vetor nulo de tamanho 10.

In [64]:
import numpy as np
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Problema 2. 
Como encontrar o tamanho da memória de qualquer matriz.

In [71]:
import numpy as np
n = np.zeros(10)
print("%d bytes" % (n.size * n.itemsize))

80 bytes


## Problema 3. 
Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1.

In [61]:
import numpy as np
n = np.zeros(10)
n[4]=1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Problema 4.
Crie um vetor com valores que variam de 10 a 49.

In [4]:
import numpy as np
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#por que o for nao funciona?
import numpy as np

#for i in range(1,5):
#    n[0][i]=rd.randint(10,50)

for i in range(0, 40):
    for j in range(10,50):
        n[i]=j
print(n)

[49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49
 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49]


## Problema 5.
Inverter um vetor (o primeiro elemento se torna o último).

In [1]:
import numpy as np
n = np.arange(1,10)
nr=n[::-1]
print(n)
print(nr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


## Problema 6. 
Crie uma matriz 3x3 com valores que variam de 0 a 8.

In [4]:
import numpy as np
n = np.arange(0,9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Problema 7.
Encontre índices de elementos diferentes de zero em `[1,2,0,0,4,0 ]`.

In [12]:
import numpy as np
n = [1, 2, 0, 0, 4, 0]
print(n)

non_zero = np.nonzero(n)
print(non_zero)

[1, 2, 0, 0, 4, 0]
(array([0, 1, 4]),)


## Problema 8.
Crie uma matriz de identidade 3x3.

In [14]:
import numpy as np
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Problema 9.
Crie uma matriz 3x3x3 com valores aleatórios.

In [19]:
import numpy as np
n = np.random.rand(3,3,3)
print(n)

[[[0.11357782 0.56961137 0.39132714]
  [0.24279384 0.67683134 0.04738267]
  [0.67757619 0.46650785 0.836124  ]]

 [[0.52784387 0.82622056 0.27539537]
  [0.65462563 0.94333049 0.26109571]
  [0.51542755 0.15142669 0.25032634]]

 [[0.86756804 0.525104   0.58738127]
  [0.04426816 0.28589914 0.34012033]
  [0.35079707 0.53508234 0.27871126]]]


## Problema 10. 
Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo.

In [23]:
import numpy as np
n = np.random.rand(10,10)
print(n)

n_min=n.min()
print(n_min)

n_max=n.max()
print(n_max)

[[0.645913   0.77007937 0.65831084 0.53002585 0.55304677 0.1211849
  0.85937696 0.14715014 0.32495918 0.0937778 ]
 [0.85676318 0.32666007 0.57762085 0.08473219 0.33871405 0.83519299
  0.08184336 0.22581677 0.15088451 0.23488099]
 [0.11339305 0.88984261 0.83826906 0.99600456 0.74385093 0.60995666
  0.40492763 0.10251268 0.39751844 0.0958957 ]
 [0.87417071 0.1531939  0.36316232 0.02842379 0.11239191 0.78792561
  0.31303677 0.47346813 0.07613858 0.84737612]
 [0.21599774 0.70098143 0.347791   0.99778883 0.16869988 0.69709685
  0.37090696 0.74669325 0.58475134 0.82604256]
 [0.89388317 0.98082759 0.9743395  0.26875804 0.86870854 0.51721102
  0.74123394 0.47205567 0.83794646 0.05363112]
 [0.29056139 0.21881771 0.21761031 0.66853725 0.70972355 0.34314979
  0.87216836 0.93591324 0.87113414 0.5680317 ]
 [0.52992361 0.54979802 0.44343768 0.6239085  0.37923429 0.34017741
  0.130906   0.45369697 0.3820132  0.66184749]
 [0.63022515 0.89311235 0.91593262 0.18607826 0.55988786 0.05540857
  0.18015958 

## Problema 11.
Crie um vetor aleatório de tamanho 30 e encontre o valor médio.

In [33]:
import numpy as np
n = np.random.rand(30)
print(n)

n_media = n.mean()
print(n_media)

[0.89459031 0.89564882 0.75811593 0.23356309 0.93910306 0.28562759
 0.24129923 0.03943998 0.53038883 0.2864985  0.95676945 0.0617268
 0.30389811 0.22309524 0.9787033  0.1433271  0.86778956 0.92141459
 0.52423223 0.49989271 0.05883369 0.42137539 0.04136289 0.27024063
 0.33990394 0.15426988 0.07162945 0.71587479 0.78921238 0.31452268]
0.45874500479158087


## Problema 12.
Crie uma matriz 2D com 1 na borda e 0 dentro.

In [36]:
import numpy as np
n = np.ones((4,4))
print(n)

n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Problema 13.
Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal.

In [46]:
import numpy as np
n = np.diag(1+np.arange(4),k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Problema 14. 
Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b).

In [49]:
import numpy as np


## Problema 15. 
Subtrair a média de cada linha de uma matriz.

In [53]:
x = np.random.rand(2, 2)
print(n)

y = x - x.mean(axis=1).reshape(-1, 1)

print(y)

[[0.48076772 0.13742057 0.40754533 0.14190207 0.23147716 0.77852508
  0.87690898 0.02485014 0.77475251 0.47773273]
 [0.1346101  0.85119977 0.40913332 0.03981678 0.72355039 0.86970871
  0.42479681 0.08296    0.77455967 0.46161363]
 [0.39084435 0.67551782 0.07217564 0.28509761 0.27785387 0.4124134
  0.01926296 0.22145696 0.59355155 0.66506695]
 [0.11665133 0.17745643 0.20961304 0.3220044  0.13627855 0.15673678
  0.33915917 0.74781234 0.95210414 0.84694735]
 [0.2458417  0.98704244 0.91567281 0.14656809 0.62735213 0.38227593
  0.07852014 0.19992725 0.67734228 0.54101767]]
[[ 0.264851   -0.264851  ]
 [ 0.16295181 -0.16295181]]


## Problema 16.
Como encontrar o valor mais frequente em uma matriz?

## Problema 17.
Crie uma matriz com valores aletaórios e salve para um arquivo.

## Problema 18.
Crie uma matriz a partir de um arquivo.